
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PROGRAMME_DOMUS = 2;
  public static final int FSI = 19;
  public static final int EGAL = 29;
  public static final int SLASH = 32;
  public static final int ACOFER = 36;
  public static final int SI = 16;
  public static final int ASSOCIER = 14;
  public static final int VIRGULE = 40;
  public static final int METHODE = 20;
  public static final int INF = 30;
  public static final int PAROUV = 33;
  public static final int TYPE_APPAREIL = 21;
  public static final int DECLARATION_SCENARII = 5;
  public static final int SCENARIO = 7;
  public static final int EOF = 0;
  public static final int FAIT = 10;
  public static final int error = 1;
  public static final int FAIRE = 9;
  public static final int POURTOUT = 8;
  public static final int IDENT = 26;
  public static final int SINON = 18;
  public static final int TYPE_AUTRE_APPAREIL = 22;
  public static final int ALORS = 17;
  public static final int DEUX_PT = 39;
  public static final int PARFER = 34;
  public static final int DECLARATION_INTERFACES = 4;
  public static final int AUTRE_APPAREIL = 23;
  public static final int MESSAGE = 12;
  public static final int POINT = 37;
  public static final int DECLARATION_APPAREILS = 3;
  public static final int PROGRAMMER = 13;
  public static final int TYPE_INTERFACE = 24;
  public static final int SUP = 31;
  public static final int ACOOUV = 35;
  public static final int UNDERSCORE = 41;
  public static final int DEFINIR = 11;
  public static final int ENTIER = 28;
  public static final int PT_VIRG = 38;
  public static final int DECLARATION_COMMANDES = 6;
  public static final int CHAINE = 27;
  public static final int EXECUTER_SCENARIO = 15;
  public static final int ENUM_ETAT = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAMME_DOMUS",
  "DECLARATION_APPAREILS",
  "DECLARATION_INTERFACES",
  "DECLARATION_SCENARII",
  "DECLARATION_COMMANDES",
  "SCENARIO",
  "POURTOUT",
  "FAIRE",
  "FAIT",
  "DEFINIR",
  "MESSAGE",
  "PROGRAMMER",
  "ASSOCIER",
  "EXECUTER_SCENARIO",
  "SI",
  "ALORS",
  "SINON",
  "FSI",
  "METHODE",
  "TYPE_APPAREIL",
  "TYPE_AUTRE_APPAREIL",
  "AUTRE_APPAREIL",
  "TYPE_INTERFACE",
  "ENUM_ETAT",
  "IDENT",
  "CHAINE",
  "ENTIER",
  "EGAL",
  "INF",
  "SUP",
  "SLASH",
  "PAROUV",
  "PARFER",
  "ACOOUV",
  "ACOFER",
  "POINT",
  "PT_VIRG",
  "DEUX_PT",
  "VIRGULE",
  "UNDERSCORE"
  };
}

