
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java.io.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\072\000\002\002\015\000\002\002\004\000\002\003" +
    "\005\000\002\003\003\000\002\004\012\000\002\005\004" +
    "\000\002\005\003\000\002\006\005\000\002\006\010\000" +
    "\002\006\011\000\002\006\003\000\002\007\012\000\002" +
    "\010\004\000\002\010\002\000\002\011\005\000\002\011" +
    "\003\000\002\012\012\000\002\013\004\000\002\013\003" +
    "\000\002\014\014\000\002\014\003\000\002\015\004\000" +
    "\002\015\003\000\002\016\003\000\002\016\003\000\002" +
    "\016\005\000\002\016\007\000\002\016\006\000\002\016" +
    "\003\000\002\017\012\000\002\017\012\000\002\017\015" +
    "\000\002\017\012\000\002\020\010\000\002\020\012\000" +
    "\002\021\010\000\002\031\003\000\002\031\005\000\002" +
    "\022\005\000\002\022\003\000\002\023\003\000\002\023" +
    "\003\000\002\023\003\000\002\024\012\000\002\025\004" +
    "\000\002\025\003\000\002\026\007\000\002\026\011\000" +
    "\002\026\007\000\002\026\011\000\002\026\003\000\002" +
    "\027\005\000\002\027\003\000\002\030\015\000\002\030" +
    "\015\000\002\030\015\000\002\030\015\000\002\030\015" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\332\000\004\040\004\001\002\000\004\004\007\001" +
    "\002\000\004\002\006\001\002\000\004\002\000\001\002" +
    "\000\004\041\010\001\002\000\004\040\011\001\002\000" +
    "\004\005\303\001\002\000\004\040\013\001\002\000\004" +
    "\006\266\001\002\000\004\040\015\001\002\000\004\007" +
    "\136\001\002\000\004\040\017\001\002\000\004\010\025" +
    "\001\002\000\004\040\021\001\002\000\004\042\022\001" +
    "\002\000\004\004\023\001\002\000\004\041\024\001\002" +
    "\000\004\002\001\001\002\000\004\041\026\001\002\000" +
    "\010\003\031\017\033\020\027\001\002\000\004\034\123" +
    "\001\002\000\004\040\117\001\002\000\012\003\uffcf\017" +
    "\uffcf\020\uffcf\040\uffcf\001\002\000\012\003\031\017\033" +
    "\020\027\040\uffd4\001\002\000\004\034\034\001\002\000" +
    "\004\037\035\001\002\000\006\043\037\045\040\001\002" +
    "\000\004\047\115\001\002\000\006\036\050\053\047\001" +
    "\002\000\004\043\037\001\002\000\006\046\uffcd\052\uffcd" +
    "\001\002\000\006\046\044\052\043\001\002\000\004\043" +
    "\037\001\002\000\004\047\045\001\002\000\012\003\uffd0" +
    "\017\uffd0\020\uffd0\040\uffd0\001\002\000\006\046\uffce\052" +
    "\uffce\001\002\000\004\052\104\001\002\000\004\052\051" +
    "\001\002\000\006\036\053\053\052\001\002\000\004\052" +
    "\075\001\002\000\004\052\054\001\002\000\006\036\056" +
    "\053\055\001\002\000\004\052\070\001\002\000\004\052" +
    "\057\001\002\000\006\036\061\053\060\001\002\000\004" +
    "\052\065\001\002\000\004\052\062\001\002\000\004\036" +
    "\063\001\002\000\004\044\064\001\002\000\010\046\uffcc" +
    "\047\uffcc\052\uffcc\001\002\000\004\036\066\001\002\000" +
    "\004\044\067\001\002\000\010\046\uffc8\047\uffc8\052\uffc8" +
    "\001\002\000\004\036\071\001\002\000\004\052\072\001" +
    "\002\000\004\036\073\001\002\000\004\044\074\001\002" +
    "\000\010\046\uffc9\047\uffc9\052\uffc9\001\002\000\004\036" +
    "\076\001\002\000\004\052\077\001\002\000\004\036\100" +
    "\001\002\000\004\052\101\001\002\000\004\036\102\001" +
    "\002\000\004\044\103\001\002\000\010\046\uffca\047\uffca" +
    "\052\uffca\001\002\000\004\036\105\001\002\000\004\052" +
    "\106\001\002\000\004\036\107\001\002\000\004\052\110" +
    "\001\002\000\004\036\111\001\002\000\004\052\112\001" +
    "\002\000\004\036\113\001\002\000\004\044\114\001\002" +
    "\000\010\046\uffcb\047\uffcb\052\uffcb\001\002\000\012\003" +
    "\uffd1\017\uffd1\020\uffd1\040\uffd1\001\002\000\004\040\uffd5" +
    "\001\002\000\004\042\120\001\002\000\004\010\121\001" +
    "\002\000\004\041\122\001\002\000\004\040\uffd6\001\002" +
    "\000\004\037\124\001\002\000\006\034\125\045\126\001" +
    "\002\000\004\047\135\001\002\000\004\034\130\001\002" +
    "\000\004\046\133\001\002\000\010\046\ufffe\047\ufffe\052" +
    "\131\001\002\000\004\034\130\001\002\000\006\046\uffff" +
    "\047\uffff\001\002\000\004\047\134\001\002\000\012\003" +
    "\uffd2\017\uffd2\020\uffd2\040\uffd2\001\002\000\012\003\uffd3" +
    "\017\uffd3\020\uffd3\040\uffd3\001\002\000\004\041\137\001" +
    "\002\000\006\003\142\040\141\001\002\000\006\003\142" +
    "\040\261\001\002\000\004\011\144\001\002\000\006\003" +
    "\uffed\040\uffed\001\002\000\006\003\uffef\040\uffef\001\002" +
    "\000\004\034\145\001\002\000\004\041\146\001\002\000" +
    "\016\003\155\012\153\016\152\021\157\022\160\034\150" +
    "\001\002\000\026\003\uffea\012\uffea\014\uffea\016\uffea\021" +
    "\uffea\022\uffea\024\uffea\025\uffea\034\uffea\040\uffea\001\002" +
    "\000\004\047\256\001\002\000\026\003\155\012\153\014" +
    "\uffeb\016\152\021\157\022\160\024\uffeb\025\uffeb\034\150" +
    "\040\uffeb\001\002\000\004\043\243\001\002\000\004\034" +
    "\213\001\002\000\004\040\206\001\002\000\026\003\uffe5" +
    "\012\uffe5\014\uffe5\016\uffe5\021\uffe5\022\uffe5\024\uffe5\025" +
    "\uffe5\034\uffe5\040\uffe5\001\002\000\026\003\uffe9\012\uffe9" +
    "\014\uffe9\016\uffe9\021\uffe9\022\uffe9\024\uffe9\025\uffe9\034" +
    "\uffe9\040\uffe9\001\002\000\004\034\204\001\002\000\004" +
    "\043\161\001\002\000\006\033\174\034\175\001\002\000" +
    "\004\023\163\001\002\000\016\003\155\012\153\016\152" +
    "\021\157\022\160\034\150\001\002\000\006\024\165\025" +
    "\166\001\002\000\016\003\155\012\153\016\152\021\157" +
    "\022\160\034\150\001\002\000\004\050\167\001\002\000" +
    "\026\003\uffe0\012\uffe0\014\uffe0\016\uffe0\021\uffe0\022\uffe0" +
    "\024\uffe0\025\uffe0\034\uffe0\040\uffe0\001\002\000\004\025" +
    "\171\001\002\000\004\050\172\001\002\000\026\003\uffdf" +
    "\012\uffdf\014\uffdf\016\uffdf\021\uffdf\022\uffdf\024\uffdf\025" +
    "\uffdf\034\uffdf\040\uffdf\001\002\000\004\037\200\001\002" +
    "\000\010\037\uffdd\044\uffdd\052\uffdd\001\002\000\004\047" +
    "\176\001\002\000\004\026\177\001\002\000\010\037\uffdc" +
    "\044\uffdc\052\uffdc\001\002\000\004\037\201\001\002\000" +
    "\006\033\174\034\175\001\002\000\004\044\203\001\002" +
    "\000\004\023\uffde\001\002\000\004\050\205\001\002\000" +
    "\026\003\uffe8\012\uffe8\014\uffe8\016\uffe8\021\uffe8\022\uffe8" +
    "\024\uffe8\025\uffe8\034\uffe8\040\uffe8\001\002\000\004\042" +
    "\207\001\002\000\004\011\210\001\002\000\004\034\211" +
    "\001\002\000\004\041\212\001\002\000\006\003\uffee\040" +
    "\uffee\001\002\000\004\051\214\001\002\000\010\027\216" +
    "\031\215\034\217\001\002\000\006\013\230\043\231\001" +
    "\002\000\004\013\224\001\002\000\004\013\220\001\002" +
    "\000\016\003\155\012\153\016\152\021\157\022\160\034" +
    "\150\001\002\000\004\014\222\001\002\000\004\050\223" +
    "\001\002\000\026\003\uffe1\012\uffe1\014\uffe1\016\uffe1\021" +
    "\uffe1\022\uffe1\024\uffe1\025\uffe1\034\uffe1\040\uffe1\001\002" +
    "\000\016\003\155\012\153\016\152\021\157\022\160\034" +
    "\150\001\002\000\004\014\226\001\002\000\004\050\227" +
    "\001\002\000\026\003\uffe4\012\uffe4\014\uffe4\016\uffe4\021" +
    "\uffe4\022\uffe4\024\uffe4\025\uffe4\034\uffe4\040\uffe4\001\002" +
    "\000\016\003\155\012\153\016\152\021\157\022\160\034" +
    "\150\001\002\000\004\030\232\001\002\000\004\044\233" +
    "\001\002\000\004\013\234\001\002\000\016\003\155\012" +
    "\153\016\152\021\157\022\160\034\150\001\002\000\004" +
    "\014\236\001\002\000\004\050\237\001\002\000\026\003" +
    "\uffe2\012\uffe2\014\uffe2\016\uffe2\021\uffe2\022\uffe2\024\uffe2" +
    "\025\uffe2\034\uffe2\040\uffe2\001\002\000\004\014\241\001" +
    "\002\000\004\050\242\001\002\000\026\003\uffe3\012\uffe3" +
    "\014\uffe3\016\uffe3\021\uffe3\022\uffe3\024\uffe3\025\uffe3\034" +
    "\uffe3\040\uffe3\001\002\000\010\033\174\034\246\035\247" +
    "\001\002\000\006\044\uffda\052\uffda\001\002\000\006\044" +
    "\uffd7\052\uffd7\001\002\000\010\044\uffd8\047\176\052\uffd8" +
    "\001\002\000\006\044\uffd9\052\uffd9\001\002\000\006\044" +
    "\252\052\251\001\002\000\010\033\174\034\246\035\247" +
    "\001\002\000\004\050\253\001\002\000\026\003\uffe7\012" +
    "\uffe7\014\uffe7\016\uffe7\021\uffe7\022\uffe7\024\uffe7\025\uffe7" +
    "\034\uffe7\040\uffe7\001\002\000\006\044\uffdb\052\uffdb\001" +
    "\002\000\012\014\uffec\024\uffec\025\uffec\040\uffec\001\002" +
    "\000\004\026\257\001\002\000\004\050\260\001\002\000" +
    "\026\003\uffe6\012\uffe6\014\uffe6\016\uffe6\021\uffe6\022\uffe6" +
    "\024\uffe6\025\uffe6\034\uffe6\040\uffe6\001\002\000\006\011" +
    "\144\042\263\001\002\000\006\003\ufff0\040\ufff0\001\002" +
    "\000\004\007\264\001\002\000\004\041\265\001\002\000" +
    "\004\040\ufff1\001\002\000\004\041\267\001\002\000\010" +
    "\003\271\032\273\040\ufff4\001\002\000\010\003\271\032" +
    "\273\040\ufff4\001\002\000\010\003\ufff2\032\ufff2\040\ufff2" +
    "\001\002\000\004\040\276\001\002\000\004\034\130\001" +
    "\002\000\004\047\275\001\002\000\010\003\ufff3\032\ufff3" +
    "\040\ufff3\001\002\000\004\042\277\001\002\000\004\006" +
    "\300\001\002\000\004\041\301\001\002\000\004\040\ufff6" +
    "\001\002\000\004\040\ufff5\001\002\000\004\041\304\001" +
    "\002\000\012\003\307\015\305\027\310\031\306\001\002" +
    "\000\004\034\327\001\002\000\004\043\322\001\002\000" +
    "\014\003\ufff7\015\ufff7\027\ufff7\031\ufff7\040\ufff7\001\002" +
    "\000\004\034\130\001\002\000\004\040\314\001\002\000" +
    "\014\003\307\015\305\027\310\031\306\040\ufffb\001\002" +
    "\000\004\040\ufffc\001\002\000\004\042\315\001\002\000" +
    "\004\005\316\001\002\000\004\041\317\001\002\000\004" +
    "\040\ufffd\001\002\000\004\047\321\001\002\000\014\003" +
    "\ufffa\015\ufffa\027\ufffa\031\ufffa\040\ufffa\001\002\000\004" +
    "\030\323\001\002\000\004\044\324\001\002\000\004\034" +
    "\130\001\002\000\004\047\326\001\002\000\014\003\ufff9" +
    "\015\ufff9\027\ufff9\031\ufff9\040\ufff9\001\002\000\004\037" +
    "\330\001\002\000\004\045\331\001\002\000\004\034\130" +
    "\001\002\000\004\046\333\001\002\000\004\047\334\001" +
    "\002\000\014\003\ufff8\015\ufff8\027\ufff8\031\ufff8\040\ufff8" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\332\000\004\002\004\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\004\011\001\001\000\002\001\001\000\004\007\013\001" +
    "\001\000\002\001\001\000\004\012\015\001\001\000\002" +
    "\001\001\000\004\024\017\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\025" +
    "\027\026\031\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\025\115\026\031\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\030\035\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\027\041\030" +
    "\040\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\030\045\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\003\126" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\003" +
    "\131\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\013" +
    "\137\014\142\001\001\000\004\014\261\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\015\153\016\150\017\146" +
    "\020\155\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\015\254\016\150\017\146\020\155\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\021\161" +
    "\001\001\000\004\031\172\001\001\000\002\001\001\000" +
    "\012\015\163\016\150\017\146\020\155\001\001\000\002" +
    "\001\001\000\012\015\167\016\150\017\146\020\155\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\031\201\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\015\220\016\150\017\146\020\155" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\015\224\016\150\017\146\020\155\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\015\237\016\150\017\146\020\155\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\015" +
    "\234\016\150\017\146\020\155\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\022\247\023\243" +
    "\031\244\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\023\253\031\244\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\010\271\011\267\001" +
    "\001\000\006\010\301\011\267\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\003\273\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\005\310\006\311\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\003" +
    "\317\001\001\000\002\001\001\000\006\005\312\006\311" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\003\324\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\003\331\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	public static void main(String args[]) throws Exception {
	new parser(new Yylex(new InputStreamReader(System.in))).parse();
	}

	public void syntax_error(Symbol cur_token) { 
		// n'interrompt pas la compil... 
		// on est par defaut dans l'etat error qui permet ensuite la recup
		// par d�faut : report_error("syntax error", null);
		report_error("Syntaxe incorrecte <"+tokenToString(cur_token)+">", null);        
	}

	public void report_error(String message, Object info) {   
		// n'interrompt pas la compil
		if (info == null) System.err.println("Mon erreur <"+ ptext()+ "> ligne "+ pline() + ", colonne " + pcolumn() + " : " + message);
		else System.err.println("Mon erreur <"+ptext()+ "> ligne "+ pline() + ", colonne " + pcolumn() + " : " +message+" : "+info);
		System.err.println("-> mais on continue l'analyse... ");
	}

	public void unrecovered_syntax_error(Symbol cur_token) {
    	// par defaut : report_fatal_error("Couldn't repair and continue parse", null);
		// on n'a pas reussi a faire de la recup
		report_fatal_error("Recuperation impossible <"+tokenToString(cur_token)+">", null);   // interrompt la compil     
	}

	public void report_fatal_error(String message, Object info) {  
		// qd cette fct est appelee, message vaut par defaut "Couldn't repair and continue parse"
		String m = "Mon erreur fatale <"+ ptext()+ "> ligne " + pline() + ", colonne " + pcolumn() + " : " + message;
		if (info == null) System.err.println(m);
		else System.err.println(m+" : "+info);
		System.err.println("-> arr�t de l'analyse...");
		done_parsing(); // interrompt la compil
  	}

	public int pline(){
		return ((Yylex)getScanner()).getYyLine();
	}
	public int pcolumn(){
		return ((Yylex)getScanner()).getYyColumn();
	}
	public String ptext(){
		return ((Yylex)getScanner()).getYyText();
	}


public String tokenToString (Symbol token) {
// qqs exemples pour voir...
     switch (token.sym) {
	case sym.SI : return "SI"; 
	case sym.CHAINE : return "CHAINE "+token.value;  
	case sym.ENTIER : return "ENTIER "+token.value;  
	//  ... A compl�ter !!
	default : return "Token impr�vu ou error";
	}
}



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {



void exemple_de_fonction(String i1, String i2)
{
	String m = "Erreur syntaxique <"+i2+"> au lieu de <"+i1+">";
	if (!(i1.equals(i2))) parser.report_error(m,null);	 
}




  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // prog ::= INF PROGRAMME_DOMUS SUP zone_decla_appareils zone_decla_interfaces zone_decla_scenariis zone_decla_commandes INF SLASH PROGRAMME_DOMUS SUP 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("prog",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= prog EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // liste_ident ::= IDENT VIRGULE liste_ident 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("liste_ident",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // liste_ident ::= IDENT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("liste_ident",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // zone_decla_appareils ::= INF DECLARATION_APPAREILS SUP liste_action_appareil INF SLASH DECLARATION_APPAREILS SUP 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("zone_decla_appareils",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // liste_action_appareil ::= action_appareil liste_action_appareil 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("liste_action_appareil",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // liste_action_appareil ::= action_appareil 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("liste_action_appareil",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // action_appareil ::= TYPE_APPAREIL liste_ident POINT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("action_appareil",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // action_appareil ::= AUTRE_APPAREIL PAROUV TYPE_AUTRE_APPAREIL PARFER liste_ident POINT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("action_appareil",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // action_appareil ::= DEFINIR IDENT EGAL ACOOUV liste_ident ACOFER POINT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("action_appareil",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // action_appareil ::= error 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("action_appareil",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // zone_decla_interfaces ::= INF DECLARATION_INTERFACES SUP liste_action_interface INF SLASH DECLARATION_INTERFACES SUP 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("zone_decla_interfaces",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // liste_action_interface ::= action_interface liste_action_interface 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("liste_action_interface",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // liste_action_interface ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("liste_action_interface",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // action_interface ::= TYPE_INTERFACE liste_ident POINT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("action_interface",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // action_interface ::= error 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("action_interface",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // zone_decla_scenariis ::= INF DECLARATION_SCENARII SUP liste_declaration_scenarii INF SLASH DECLARATION_SCENARII SUP 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("zone_decla_scenariis",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // liste_declaration_scenarii ::= liste_declaration_scenarii declaration_scenarii 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("liste_declaration_scenarii",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // liste_declaration_scenarii ::= declaration_scenarii 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("liste_declaration_scenarii",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // declaration_scenarii ::= INF SCENARIO IDENT SUP liste_action_scenarii INF SLASH SCENARIO IDENT SUP 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaration_scenarii",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // declaration_scenarii ::= error 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaration_scenarii",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // liste_action_scenarii ::= action_scenarii liste_action_scenarii 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("liste_action_scenarii",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // liste_action_scenarii ::= action_scenarii 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("liste_action_scenarii",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // action_scenarii ::= boucle_pourtout 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("action_scenarii",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // action_scenarii ::= conditionnelle 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("action_scenarii",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // action_scenarii ::= EXECUTER_SCENARIO IDENT PT_VIRG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("action_scenarii",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // action_scenarii ::= MESSAGE PAROUV parametre_message PARFER PT_VIRG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("action_scenarii",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // action_scenarii ::= IDENT POINT METHODE PT_VIRG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("action_scenarii",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // action_scenarii ::= error 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("action_scenarii",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // boucle_pourtout ::= POURTOUT IDENT DEUX_PT TYPE_APPAREIL FAIRE liste_action_scenarii FAIT PT_VIRG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("boucle_pourtout",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // boucle_pourtout ::= POURTOUT IDENT DEUX_PT AUTRE_APPAREIL FAIRE liste_action_scenarii FAIT PT_VIRG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("boucle_pourtout",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // boucle_pourtout ::= POURTOUT IDENT DEUX_PT AUTRE_APPAREIL PAROUV TYPE_AUTRE_APPAREIL PARFER FAIRE liste_action_scenarii FAIT PT_VIRG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("boucle_pourtout",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // boucle_pourtout ::= POURTOUT IDENT DEUX_PT IDENT FAIRE liste_action_scenarii FAIT PT_VIRG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("boucle_pourtout",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // conditionnelle ::= SI condition ALORS liste_action_scenarii FSI PT_VIRG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("conditionnelle",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // conditionnelle ::= SI condition ALORS liste_action_scenarii SINON liste_action_scenarii FSI PT_VIRG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("conditionnelle",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // condition ::= PAROUV etat EGAL EGAL etat PARFER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("condition",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // etat ::= ENUM_ETAT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("etat",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // etat ::= IDENT POINT METHODE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("etat",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // parametre_message ::= parametre_message VIRGULE contenu_message 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametre_message",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // parametre_message ::= contenu_message 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametre_message",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // contenu_message ::= CHAINE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("contenu_message",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // contenu_message ::= IDENT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("contenu_message",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // contenu_message ::= etat 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("contenu_message",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // zone_decla_commandes ::= INF DECLARATION_COMMANDES SUP liste_action_commande INF SLASH DECLARATION_COMMANDES SUP 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("zone_decla_commandes",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // liste_action_commande ::= action_commande liste_action_commande 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("liste_action_commande",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // liste_action_commande ::= action_commande 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("liste_action_commande",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // action_commande ::= ASSOCIER IDENT EGAL IDENT POINT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("action_commande",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // action_commande ::= ASSOCIER IDENT EGAL ACOOUV liste_ident ACOFER POINT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("action_commande",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // action_commande ::= PROGRAMMER IDENT EGAL date POINT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("action_commande",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // action_commande ::= PROGRAMMER IDENT EGAL ACOOUV liste_date ACOFER POINT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("action_commande",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // action_commande ::= error 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("action_commande",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // liste_date ::= liste_date VIRGULE date 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("liste_date",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // liste_date ::= date 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("liste_date",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // date ::= PAROUV ENTIER VIRGULE ENTIER VIRGULE ENTIER VIRGULE ENTIER VIRGULE ENTIER PARFER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("date",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // date ::= PAROUV UNDERSCORE VIRGULE ENTIER VIRGULE ENTIER VIRGULE ENTIER VIRGULE ENTIER PARFER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("date",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // date ::= PAROUV ENTIER VIRGULE UNDERSCORE VIRGULE ENTIER VIRGULE ENTIER VIRGULE ENTIER PARFER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("date",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // date ::= PAROUV ENTIER VIRGULE ENTIER VIRGULE UNDERSCORE VIRGULE ENTIER VIRGULE ENTIER PARFER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("date",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // date ::= PAROUV ENTIER VIRGULE ENTIER VIRGULE ENTIER VIRGULE UNDERSCORE VIRGULE ENTIER PARFER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("date",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
